### ISSUE TITLE
User can't ping the device via hostname on local mode.

### ISSUE THREAD

**Issue by dansku** [balena-os/balena-supervisor#1100]
User can't ping the device hostname when working with local mode, which doesn't happen normally

https://jel.ly.fish/view-all-support-threads...properties.data.properties.status+is+open/support-thread-front-cnv-325gv9f

**Comment by cywang117** [comment]
Closing; no longer reproducible. If you see this issue, please first try upgrading the Supervisor to latest, then if the issue persists, please paste Supervisor logs with this ticket using `journalctl -u balena-supervisor -xef -n 100`.
