### ISSUE TITLE
IPv6 addresses not exposed in supervisor API

### ISSUE THREAD

**Issue by heri16** [balena-os/balena-supervisor#1114]
Only IPv4 addresses is exposed as ip_address in the API.

IPv6 addresses could also be exposed.

https://github.com/balena-io/balena-supervisor/blob/0871f05445fd7edf7a25fec38bca4fad0eb5cfd8/src/network.ts#L130

**Comment by pipex** [comment]
Added in [v12.11.33](https://github.com/balena-os/balena-supervisor/blob/master/CHANGELOG.md#v121133)
