### ISSUE TITLE
Race condition between user containers and balena-engine api

### ISSUE THREAD

**Issue by robertgzr** [balena-os/balena-supervisor#1231]
... leads to `/var/run/balena.sock` being created as a directory on the host.

This can happen after the user containers have been created and started when we reboot the device/ restart balena-engine.
The engine brings up previously started containers and it's own API (including the socket) in parallel, leading to a race condition when the `--volume` flag was used for creating the containers.

One solution on the supervisor side would be to switch to the `--mount` notation (or it's equivalent in docker-compose) which does not auto-create the source of the bind mount as a directory if it is missing on the host.

Related: 
* https://github.com/balena-os/meta-balena/issues/1748
* https://github.com/moby/moby/issues/30348

**Comment by robertgzr** [comment]
another quick solution would be to force containers that mount the balena socket to have the restart policy set to off. This would move the responsibility of starting the container to the supervisor rather than the engine and thus avoid the race

**Comment by robertgzr** [comment]
it looks like this can still happen with application containers that have access to the balena socket

see https://www.flowdock.com/app/rulemotion/balenalabs/threads/chG_M67A0Va0Bl2cgLiZ4pdCelh

**Comment by robertgzr** [comment]
The supervisor should use the `mounts` field instead of [`binds`](https://github.com/balena-io/balena-supervisor/blob/f8cc2bc0cea362ea0d3dec3e564028f918f64dca/src/compose/service.ts#L692
) for mounting host paths into the container: 

see:
* https://github.com/moby/moby/issues/30348#issuecomment-532285233
* https://docs.docker.com/engine/api/v1.40/#operation/ContainerCreate

**Comment by robertgzr** [comment]
this comes with the caveat that container start will fail if the source path doesn't exist, which needs to be handled

**Comment by pipex** [comment]
This issue was fixed by in #1946
