### ISSUE TITLE
Blink doesn't work on pi4

### ISSUE THREAD

**Issue by CameronDiver** [balena-os/balena-supervisor#1264]

**Comment by cywang117** [comment]
Closing; not able to reproduce and not enough info here. If this was an error, please re-open with Supervisor and OS versions, and the output of `balena exec -it balena_supervisor env | grep 'LED_FILE'`.

**Comment by cywang117** [comment]
Thanks @theashyster , what's the OS version you encountered this on?

**Comment by cywang117** [comment]
Thanks @theashyster . Will look into this when I get a chance, feel free to follow this issue for updates, or if so interested, to contribute a fix :)
