### ISSUE TITLE
Applying device configuration does not respect update lock when it is enabled 

### ISSUE THREAD

**Issue by rahul-thakoor** [balena-os/balena-supervisor#1267]
When a device has `Update Locking` enabled, subsequent changes in device configurations shouldn't be applied immediately. These changes should be applied if update lock once update lock is disabled. 

**Steps to reproduce:**
1. Enable Update Locking from Actions tab of a device
![image](https://user-images.githubusercontent.com/13220877/79310356-da7a3a80-7f0c-11ea-886e-80d90cd157e1.png)

2.  Add a custom configuration variable for the device in device configuration tab

**Expected behavior:**

Device should not apply the variable and restart

**What happens:**

Custom  variable is applied and device restarts immediately

**Comment by 20k-ultra** [comment]
@rahul-thakoor the screenshot you have in this issue says to enable lock override which will ignore locks and apply configurations. So your description of what happens is correct.
