### ISSUE TITLE
Add a cache in front of the database to reduce connection pool filling

### ISSUE THREAD

**Issue by CameronDiver** [balena-os/balena-supervisor#1316]
We use a sqlite database in a file which has the limitation that only a single connection can be made at any one time: https://github.com/knex/knex/issues/2820

To get around this, and avoid hitting the database as much as possible, we should store every read and write in memory, as well as writing every change to the database. Given that the data changes very infrequently in most cases, we can achieve a good amount of load on the database (and by extension the storage medium).

The simplest and first implementation of this would simple cache all values from the config table, which is a large part of the database traffic at the moment.

Related: https://github.com/balena-io/balena-supervisor/issues/987

**Comment by cywang117** [comment]
Closing as the Supervisor database rarely changes so a cache may be overkill. In the linked ticket, we eventually determined that the issue wasn't related to the Supervisor database connection limitation, but rather the user application using all the inodes.
