### ISSUE TITLE
Feature request: Interpolate BALENA_* values set in dashboard vars

### ISSUE THREAD

**Issue by woosteln** [balena-os/balena-supervisor#1343]
When deploying a generic, non balena-oriented, service within an application, I would like to be able to set configuration variables to values provided by the balena supervisor at service run time.

Contrived example: I have a 3rd party service that sends data via mqtt back to my cloud server. I would like to set its configurable environment variable `MQTT_USER` to the value represented by `BALENA_DEVICE_UUID` without having to update the source code of the application to be specifically aware of `BALENA_DEVICE_UUID`. (Imagine its a closed source 3rd party app in binary form and the only control I have over it is via setting environment variables on the container).

Ideally, any variables specified here https://www.balena.io/docs/learn/develop/runtime/#environment-variables could be set as values in the Environment, Service or Device level variables in the Balena Dashboard, and values would be substituted at runtime.

So for example in the balena application dashboard I would add a new environment or service variable:

```
NAME: MQTT_USER
VALUE: ${BALENA_DEVICE_UUID}
```

And when the service was run it would see `$MQTT_USER=XXXXXXXXXXXXXXX` with the locally scoped value of the variable.

While the docker-compose file for an application cannot support interpolation, likely due to the layers of processing it goes through in the build process ( https://www.balena.io/docs/reference/supervisor/docker-compose/#known-unsupported-features ) it would be incredibly useful to be able to set variables in the dashboard to BALENA_* values that can be interpolated at runtime to avoid binding application code to balena, and enable easy integration of third party application images.

**Comment by CameronDiver** [comment]
@woosteln I think I'm missing your intent a little bit here, but why would setting a device-specific environment variable with `MQTT_USER=<device_uuid>` not work for you?

**Comment by woosteln** [comment]
Hi Cameron. I could set the value for each devices individually, but doing that at large fleet sizes would be impractical and potentially error prone. (Unless I've missed something. Have tried that string literal `<device_uuid>` as an env value, but it seems to be interpreted literally, although removing the leading `<`.)

To work around that, I could create a script that uses the api and periodically updates all devices to have that value set to their own device id. This feels less precise, and results in another process to manage.

Having a rules based method to apply a device specific value that is already managed by Balena at an application level would be optimal for large fleet deployments where every device in the fleet should have a particular key to its device specific value.

**Comment by CameronDiver** [comment]
I see, this does indeed make a lot of sense, and we've spoken about similar things in the past. I do like the idea, and I would like to see this get implemented.

I can't give you a time frame right now unfortunately as there's a few other things going on, but I do plan to try and get some time to do this.

Thanks for the suggestion!

**Comment by woosteln** [comment]
No worries. I'm just beginning to engage with the Balena ecosystem, and kicking the tyres.
I might have time to submit a speculative PR if that might be any use.

**Comment by qvntra** [comment]
@woosteln how did you end up proceeding forward from here? I am looking to inject BALENA_DEVICE_UUID for AWS IoT - Device JITR whitelisting. It would also be great to set our Mosquitto MQTT Bridge client_id to BALENA_DEVICE_UUID.

**Comment by woosteln** [comment]
Hi @qvntra in the short term, we've just applied the value of BALENA_DEVICE_UUID to a device+service var.
I was going to, but haven't had the time, to propose an update to:
I think @CameronDiver  and @20k-ultra  might be able to provide more info on progress, but looks like its moving forward.

**Comment by qvntra** [comment]
@woosteln could you elaborate a bit further on what you mean by applying the value of BALENA_DEVICE_UUID to a device+service var?

**Comment by cywang117** [comment]
For feature requests such as these, we encourage adding them as requests to our [public roadmap](https://roadmap.balena.io/). Looking forward to seeing this topic there!

For the specific contrived use case above of "set MQTT_USER equal to the value of BALENA_DEVICE_UUID", it sounds like exporting MQTT_USER as follows in an `entry.sh` script is an easy way to achieve this:
```shell
#!/bin/sh
MQTT_USER="$BALENA_DEVICE_UUID"
export MQTT_USER
# Command to launch main process. MQTT_USER will be set and available under `process.env` in the case of Node.
node app.js
```

This script can easily to used to export any number of Supervisor-provided env vars with your custom variable names. To get a list of what the Supervisor provides, try `balena exec $(balena ps -aq -f name=YOUR_SERVICE) env`. 

As I don't fully understand the benefit of the original proposed implementation over the method I mentioned in this comment, I'm closing this issue; if this was an error, please do create a feature request in our public roadmap and we'll discuss through there instead of GitHub. Thank you!
