### ISSUE TITLE
Modifications to firewall (iptables) always removed by Supervisor

### ISSUE THREAD

**Issue by 20k-ultra** [balena-os/balena-supervisor#1482]
The Supervisor has added firewall configuration functionality in v11.9.1 which applies rules based on a mode. If a user wants to apply their own iptable rules they would use `BALENA_HOST_FIREWALL_MODE=off` configuration variable however it has been reported and reproduced that this is not the behaviour.

If you set rules in iptable with your own service and have firewall mode set to off the Supervisor will override and remove your settings. We have created https://github.com/balena-io-playground/iptables-test which easily reproduces this behaviour.

**Comment by 20k-ultra** [comment]
For anyone that stumbles on this issue to have your iptable rules persist even when you disable the firewall mode in the Supervisor which still wipes your changes, place them into the raw table as the Supervisor only clears the filter table.

**Comment by 20k-ultra** [comment]
@pipex I know we haven't resolved this because we wanted to figure out what to do with the firewall. I think an acceptable stop gap is to at-least, make the Supervisor not clear ALL rules in iptables when the firewall mode is set to off.

**Comment by pipex** [comment]
@20k-ultra I think that is part of the solution, but I don't know how easy is to tell iptables-restore to do that. Otherwise doing that might mean a full reimplementation of the feature

**Comment by mycloudllc** [comment]
With this being a current issues is there anyway around having to set iptable rules to the raw table? I have a few mangle rules I need  to add, but upon reboot those are wiped as well. Any ideas?

**Comment by cywang117** [comment]
This fix is available with v14.9.2+ Supervisors.
