### ISSUE TITLE
Remove dependency on mz package (?)

### ISSUE THREAD

**Issue by pipex** [balena-os/balena-supervisor#1567]
The supervisor depends today on the [node modernize](https://github.com/balena-io/balena-supervisor/pull/1566) (mz) package, because of its promise support, but newer node versions have promise support builtin in the [fs package](https://nodejs.org/docs/latest-v12.x/api/fs.html#fs_fs_promises_api) and provide ways to promisify other operations such as `child_process.exec` (see the promisify example [here](https://nodejs.org/docs/latest-v12.x/api/child_process.html#child_process_child_process_exec_command_options_callback))

A code review to see what other functionality is used from that package might tell us the difficulty of this change.

**Comment by cywang117** [comment]
@pipex Did a quick code review, current `mz` methods used can easily be replaced by a combination of native `fs.promises` and `util.promisify`. See table below:
mz | Node fs | Node child_process | is promise lib?
----|---------|---------------------|-------------
child_process.exec | | exec | N
child_process.spawn | | spawn | N
fs.exists | exists (DEPRECATED, should create a helper that has the same functionality using `fs.access` or `fs.stat`) | | N
fs.fsync | fsync | | N
fs.lstat | lstat | | Y
fs.mkdir | mkdir | | Y
fs.open | open | | Y
fs.readdir | readdir | | Y
fs.readFile | readFile | | Y
fs.rename | rename | | Y
fs.stat | stat | | Y
fs.unlink | unlink | | Y
fs.watch | watch | | N
fs.write | write | | N
fs.writeFile | writeFile | | Y

Looks like a straightforward fix to decrease Supervisor's binary size *very* slightly.

**Comment by 20k-ultra** [comment]
I love removing dependencies. Some of the standard lib functions also provide performance buffs!
