### ISSUE TITLE
A network config change in the same release as an app update can make Supervisor erroneously report device state as applied when it's not applied

### ISSUE THREAD

**Issue by 20k-ultra** [balena-os/balena-supervisor#1576]
I have seen instances where a container is shown on the dashboard and in a "Downloaded" state not the desired "Running" or even "Stopped".... No matter how many times the Supervisor checks the target state even after restarting, the Supervisor won't run the image that is downloaded.

When you try to manually start it with POST /v2/applications/:app-id/start-service from the dashboard (click the Play icon) a 404 is logged. That means the Supervisor's database has somehow lost track of this container or image. That depends on what value is used in the body payload since you can start an Image by serviceId or ImageId.

**Comment by cywang117** [comment]
I made an easy reproduction repo here which can be used for investigating: https://github.com/balena-io-experimental/network-ipam-config-reproduction

**Comment by louisburton** [comment]
If we hit this issue, is there any way to manually intervene to get the service started? A workaround that doesn't involve release switching?

**Comment by cywang117** [comment]
@louisburton, I'm not quite sure. What happens if you stop & remove the containers that are on the incorrect network, restart the Supervisor?

I took a look at this issue before the holidays and ran into some confusion with it, but no worries, it's still on my list.

**Comment by louisburton** [comment]
I don't believe that worked. I will double check it next time it occurs though 👍 we have some offline devices which might bunny hop the network upgrade release.

**Comment by cywang117** [comment]
This should be fixed with [v14.10.8](https://github.com/balena-os/balena-supervisor/blob/master/CHANGELOG.md#v14108) cc @louisburton
