### ISSUE TITLE
Incorrect release commit

### ISSUE THREAD

**Issue by 20k-ultra** [balena-os/balena-supervisor#1579]
Trying to piece together the required conditions here but I am pretty confident as I've heard it twice now that a user moved their device from 1 application to another and it shows the first application's release id pointing to the new application's release id like so:

![image](https://user-images.githubusercontent.com/3946250/105799580-e4809d80-5f62-11eb-8447-5faffd12ebea.png)

This is not always the case though as seen in https://github.com/balena-io/balena-ui/pull/4513 which has an example of the same release ID pointing to itself. 

The endpoint for this data is coming from the cloud's `/v6/device` but I'm not sure what endpoint on the Supervisor that uses or if the Supervisor is pushing up local state.

**Comment by 20k-ultra** [comment]
On a device that had this issue I saw the service which was showing this issue to be running 1 container but it had 3 images for the service downloaded. 2 were in "Downloaded" state and 1 in "Running". In addition the UI showed that the device was not running on the target release. I saw that the services running were all the target release. This was due to the API response containing different commits for is_running__release and should_be_running__release. 

I believe by containing old images for a service we can recreate this release ID -> release ID and show different running release commits.

**Comment by 20k-ultra** [comment]
Issue reported in FD: https://www.flowdock.com/app/rulemotion/r-beginners/threads/oMk2P00r1XQ3I4BYl6LORt90VJA

**Comment by 20k-ultra** [comment]
This issue is also related or duplicate of https://github.com/balena-io/balena-supervisor/issues/1542

**Comment by 20k-ultra** [comment]
After querying the database on device I saw that there were 3 entries in the `images` table for `wifi-connect` service. Once I removed the 2 oldest records the device reported the correct commit running.

**Comment by cywang117** [comment]
Moving the device between applications (staging to prod for instance) while the Supervisor is downloading app updates is a common contributing factor according to the ticket I linked above ^

**Comment by pipex** [comment]
Solved by #1749
