### ISSUE TITLE
Gather all /v1/ endpoints into device-api/v1.ts

### ISSUE THREAD

**Issue by cywang117** [balena-os/balena-supervisor#1597]
All v2 endpoints are located appropriately in `device-api/v2.ts`, but v1 endpoints are scattered amongst:

- `device-api/v1.ts`
- `api-binder.ts`
- `device-state.ts`
- `supervisor-api.ts`
- `proxyvisor.js`

If v1 is not being deprecated soon, it would be a good idea (and a quick fix!) to collate some if not all of these routes into `device-api/v1.ts` for code legibility. Particularly, the organization would help newcomers understand the codebase more quickly.

I'm not sure if proxyvisor.js routes should be included in that list, as they are not mentioned in the official Supervisor API documentation.

**Comment by cywang117** [comment]
@pipex As this was mentioned in the [v1 unit tests PR](https://github.com/balena-io/balena-supervisor/pull/1589#discussion_r574482884), I'm formally adding it here 👍🏼

**Comment by 20k-ultra** [comment]
I realized this too but there's 1 endpoint I know of that will give you some trouble...

The [/v1/update](https://github.com/balena-io/balena-supervisor/blob/17b6b007780132898e7f6f6d9ee504e7ec6a1dbb/src/api-binder.ts#L586) uses a local variable called readyForUpdates and that is set to true once the Supervisor finishes some setup. That value would then need to be moved or some changes made to not have to check that value in order for the endpoint to run.

Once I found that I decided to just leave it alone....keep in mind that we should favour deprecating V1 rather then making it easier to maintain so this battle doesn't seem worth it to me...unless the changes would benefit the work you're doing with making V2 have feature parity with V1,

cc @pipex

**Comment by cywang117** [comment]
@20k-ultra Agreed, definitely not high priority in any case. I'm documenting it here since it came up in discussion. Potentially this issue can be closed once v1 actually becomes deprecated, (or now). 

Also, I don't think the distribution of the v1 endpoints would impact v2 feature parity in any significant way, so no worries.

**Comment by cywang117** [comment]
Closing this issue - agree with comment above about favoring deprecation. The v1 endpoint code doesn't get in the way, and refactoring would take more time than it's worth. When v2 is feature-complete we intend to hide v1 routes from the docs as well, so v1 will soon see even less use. The efficient way forward here is to implement v2 in such a way that consumers will be able to seamlessly switch over from v1 to v2 with no issues.
