### ISSUE TITLE
CPU temperature reporting an incorrect value to the API

### ISSUE THREAD

**Issue by pipex** [balena-os/balena-supervisor#1606]
This was reported by a user on devices with supervisor v11.14.0, where the value observed on the dashboard and the value reported by `cat /sys/class/thermal/thermal_zone0/temp` is more than 5 degrees. 

There were some changes to the diff calculation for system information in v12.0.3 and the issue doesn't seem to occur on later supervisors but looking at the code I cannot tell with certainty if the bug was fixed.

**Comment by kb2ma** [comment]
Reviewed the support thread. The issue here was device and cloud not recognizing the same measurement as the most recent, so becoming out of sync. This problem was fixed with #2049.
