### ISSUE TITLE
Not detecting storage device plugged in with USB

### ISSUE THREAD

**Issue by 20k-ultra** [balena-os/balena-supervisor#1609]
It is possible to run devices such as a rpi on a storage device which is plugged in via a USB port. The Supervisor fails to detect these types of devices and the dashboard will show no storage drive.

The culprit is probably the regex match https://github.com/balena-io/balena-supervisor/blob/dc96cca5e5fddc277d5a466bcd17654ccce67995/src/lib/system-info.ts#L26

**Comment by anujdeshpande** [comment]
hey @20k-ultra - let me know if I can do anything to help with this

**Comment by 20k-ultra** [comment]
Available in Supervisor v.12.5.8.
