### ISSUE TITLE
Document supervisor api examples need uuid to be quoted

### ISSUE THREAD

**Issue by rahul-thakoor** [balena-os/balena-supervisor#1620]
related to https://github.com/balena-io/docs/issues/1404

This works:
```
--data '{"uuid": "460d4e8becd93606f682cd64f8a26fcd"}' \
```
This leads to a Bad Request error:
```
--data '{"uuid": 460d4e8becd93606f682cd64f8a26fcd}' \
```
This error means that the request body is malformed. In this example, it failed because the JSON format requires that the UUID is quoted.

**Comment by vipulgupta2048** [comment]
Thanks, @rahul-thakoor for opening the issue, I indeed got side-tracked. Very sus though that a customer issue popped just when I was digging through year-old docs issues.
