### ISSUE TITLE
Configurable var to stop sending hardware metrics

### ISSUE THREAD

**Issue by 20k-ultra** [balena-os/balena-supervisor#1645]
For users that are sensitive to bandwidth usage we can help by offering a configurable variable to toggle sending cpu/memory/temp/storage stats to the cloud. This feature can send data every 10 seconds at a minimum so it will definitely cause devices to make more noise.

We obtain the system information at https://github.com/balena-os/balena-supervisor/blob/16f981c478f26e7947a7f8bdc2a3d8333f3031e1/src/lib/system-info.ts#L96 which is reported in the reportCurrentState function https://github.com/balena-os/balena-supervisor/blob/16f981c478f26e7947a7f8bdc2a3d8333f3031e1/src/device-state/current-state.ts#L180.

We should step in at the reportCurrentState to not ask for system info if the device is configured not to send this. We just need to figure out what default value should be used. We can either set it to have null values OR don't even set the info key in the stateForReport.local object. 

When we do this we should add the configurable var to https://github.com/balena-os/balena-supervisor/issues/1646

**Comment by 20k-ultra** [comment]
The currently agreed solution is the send null data for each value. So, cpu null, mem null, etc. Not an empty object.

additionally, we found https://github.com/balena-os/balena-supervisor/issues/1669 would be another optimization.

**Comment by cywang117** [comment]
Clarifying: send null once when flag is toggled on, update "last reported current state" as an in-memory object. Thus future reports which would contain null for sys info would filter it out based on state diff comparisons. 

@20k-ultra Does this PR depend on changes that should be made in #1669 to persist last reported current state?

**Comment by cywang117** [comment]
Additionally, `is_undervolted` as a sysinfo value is not nullable in the API. I can only assume that we would not send an `is_undervolted` field with the null payload.

**Comment by 20k-ultra** [comment]
https://github.com/balena-os/balena-supervisor/issues/1669 is just an optimization for the Supervisor in general which we could add even without this metrics work. 

I would modify the `SystemInfo` type to allow null. There are some values which already allow undefined and I'd make those null instead of undefined as well. Then with `SystemInfo` now allowing null for all the values make a function which returns a disabled report that is used like:

```
const info = (await shouldReportMetrics())
		? await sysInfo.getSysInfoToReport()
		: sysInfo.disabledReport();
```

These are just my ideas of course, other solutions can be considered.

**Comment by 20k-ultra** [comment]
As you discovered open balena doesn't allow null value for some keys right such as is_undervolted.  We'll have to identify where those restrictions are to see if what to do. Maybe it's a db table schema constraint or the API validation.

**Comment by cywang117** [comment]
is_undervolted is defined as non-nullable in the [schema](https://github.com/balena-io/open-balena-api/blob/master/src/balena-model.ts#L298). If we are patching null with all the fields, for consistency, something might need to change in the schema to allow null for this one field. I'll confirm next steps and update here.

**Comment by cywang117** [comment]
After internal discussion, `is_undervolted` is crucial enough of a metric that it will always continue to be reported. Note that this metric rarely changes, and it changes at most once during the device's life cycle (from false --> true if undervolted, but true --> false is not possible by design). So bandwidth usage concerns are minimal if not nonexistent.
