### ISSUE TITLE
Convert /src/device-api/common.js to TypeScript

### ISSUE THREAD

**Issue by cywang117** [balena-os/balena-supervisor#1650]
Most recently, [this PR](https://github.com/balena-os/balena-supervisor/pull/1635#discussion_r607009527) has encountered friction while dealing with common.js as a non-TypeScript module. I'm sure there have been other instances of friction in the past. It would benefit everyone greatly and reduce friction for future developers if we could just convert it once and for all.

**Comment by 20k-ultra** [comment]
agreed. This and https://github.com/balena-os/balena-supervisor/blob/master/src/proxyvisor.js are the last 2 js files.

**Comment by cywang117** [comment]
Closing in favor of #1660.
