### ISSUE TITLE
Supervisor may sometimes use the wrong source image for deltas

### ISSUE THREAD

**Issue by pipex** [balena-os/balena-supervisor#1729]
When the supervisor is looking for a delta source for an image, if it doesn't find one for the same app and service, it will use ANY image from the same app.

This is the code https://github.com/balena-os/balena-supervisor/blob/master/src/compose/application-manager.ts#L586-L606
It was introduced here https://github.com/balena-os/balena-supervisor/commit/cb37f7ebcc20125c6aa13f954ba38c8b91c40eda but there is no explanation, I guess is probably legacy from single container.

Replication steps

- Create an app with at least two services and provision a device (set to track latest)
- Push a couple of releases to the app to have deltas be generated
- Once the device is in the last release
   - Stop the supervisor
   - Delete the supervisor database 
   - Start the supervisor 

You'll see the logs

- `Docker image download <data for service 1>` this is harmless since the supervisor cannot find the image by name (and there is no database) it tells the engine to download it but since the image data is there, there is nothing to download
- `delta([<service 2>] <digest for service 1>) <digest for service 2>` This is the supervisor asking the delta server to calculate a delta from the image of service 1 to the image of service 2

**Comment by pipex** [comment]
Update, this is a bit racy, I haven't been able to replicate every time. The fix is easy though, creating a PR right now

**Comment by MTolba** [comment]
@pipex what are the next steps? should I inform that user that we solved the issue and give them a link?
