### ISSUE TITLE
Failed to purge data because of multiple engine resources having same name

### ISSUE THREAD

**Issue by 20k-ultra** [balena-os/balena-supervisor#1735]
When trying to use the purge function from the dashboard the Supervisor began to log:
```
Error purging data: Error: (HTTP code 400) unexpected - 2 matches found based on name: network xxxxxxx_default is ambiguous 
```

Upon looking at the device I saw (PII redacted):

```
root@xxxxxxx:~# balena network ls
NETWORK ID          NAME                DRIVER              SCOPE
0c56a75ffd65        xxxxxxx_default     bridge              local
950af398975a        xxxxxxx_default     bridge              local
133cafdb127a        bridge              bridge              local
7a48ad6a465d        host                host                local
b64601f541da        none                null                local
24ea9de53374        supervisor0         bridge              local
``` 

Could the Supervisor remove resources by ID rather then name then ?

**Comment by pipex** [comment]
I think the bug is the supervisor getting two networks with the same name. The supervisor could remove by id, but it would require storing the id in the database with potentially all the complexity that adds

**Comment by 20k-ultra** [comment]
duplicate of https://github.com/balena-os/balena-supervisor/issues/590
