### ISSUE TITLE
Remove fire emoji 🔥 from supervisor firewall logs

### ISSUE THREAD

**Issue by Hades32** [balena-os/balena-supervisor#1751]
Our logs generally don't contain emojis, with one exception: The firewall logs from the supervisor (independently of the severity level).

I think we should remove that emoji, because it distracts readers of the logs, unless they are explicitly searching for FW issues

**Comment by Hades32** [comment]
@cywang117's comment
> I'm okay with it and I think our users have gotten used to it at this point too, and since it's the only log line with an emoji attached, it makes it easy to find firewall-related info

**Comment by Hades32** [comment]
I'd argue that most of the time, users are not looking for firewall-related info, therefore the majority of cases it distracts instead of helps

**Comment by cywang117** [comment]
> I'd argue that most of the time, users are not looking for firewall-related info, therefore the majority of cases it distracts instead of helps

I don't disagree with that either 👀
