### ISSUE TITLE
Update Supervisor to use Node 16

### ISSUE THREAD

**Issue by 20k-ultra** [balena-os/balena-supervisor#1757]
Supervisor currently uses node 12 which will be EOL in 2022.

Is it worth upgrading to 14 is that will also be EOL for maintenance just 1 more year later ?

https://nodejs.org/en/about/releases/

**Comment by cywang117** [comment]
Looking at that link, Node 16 will enter Active LTS in Nov 2021, and Node 12 will exit Maintainence LTS in May 2022. How about upgrading directly to Node 16 sometime in that period?

**Comment by 20k-ultra** [comment]
Yup I cool with Node 16 over 14

**Comment by 20k-ultra** [comment]
@pipex want to share your findings from upgrading to node 16 here when you can

**Comment by pipex** [comment]
From some initial tests. As expected tests with uncaught exceptions now fail

```
Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/flalanne/Development/balena/node16/balena-supervisor/build/test/02-db.spec.js)
```

There seem to be some incompatibility of the blink module with node 16 as well

```
Unhandled rejection TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (0)
    at writeFile (node:fs:2108:5)
    at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (/usr/src/app/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
    at ledOff (/usr/src/app/node_modules/blinking/index.js:18:26)
    at Object.stop (/usr/src/app/node_modules/blinking/index.js:48:13)
    at /usr/src/app/src/network.ts:98:20
```

**Comment by cywang117** [comment]
Updated to Node 16 with Supervisor 14.1.0
