### ISSUE TITLE
Not detecting update strategy with `BALENA_SUPERVISOR_UPDATE_STRATEGY`

### ISSUE THREAD

**Issue by 20k-ultra** [balena-os/balena-supervisor#1773]
The docs say to use `BALENA_SUPERVISOR_UPDATE_STRATEGY` and this is an exact replacement of the previous value `RESIN_SUPERVISOR_UPDATE_STRATEGY` just with `BALENA_` prefix. However, if you set your update strategy with the balena prefix then the update strategy is not picked up.

Only after I switched to the resin prefix did the Supervisor apply the update strategy from the target state to the target config.

https://www.balena.io/docs/learn/deploy/release-strategy/update-strategies/

**Comment by pipex** [comment]
@20k-ultra I think this is an API issue. The API converts the ENV var into labels on the target state (which is what the supervisor looks for). If the supervisor is not getting the label, then is the API that might have an issue

**Comment by 20k-ultra** [comment]
Issue was [identified](https://github.com/balena-io/open-balena-api/issues/735) to be from the API which sets this configuration as a label in a service. We won't be resolving this issue because user's should specify the update strategy via labels in their docker-compoes file: https://www.balena.io/docs/reference/supervisor/docker-compose/#labels
