### ISSUE TITLE
supervisor.conf may get deleted on restored devices

### ISSUE THREAD

**Issue by cywang117** [balena-os/balena-supervisor#1792]
Needs more investigation, but on a device which was deleted and has been restored, a case has been observed where the `supervisor.conf` file wasn't present, meaning the Supervisor couldn't start up on the device. It's unclear what deleted this file.

We can move this issue to the appropriate repo once we determine the root cause.

**Comment by pipex** [comment]
This seems like it should be a pattern more than as a supervisor issue, as the supervisor itself never touches that file @cywang117

**Comment by cywang117** [comment]
Makes sense, I'll create a pattern instead.
