### ISSUE TITLE
Empty State Report Error

### ISSUE THREAD

**Issue by GregorR1** [balena-os/balena-supervisor#1808]
Event: Device state report failure {"error":{"message":""}}

Device is showing as (VPN ONLY).  In the balena-supervisor logs I am getting the error shown above.

The Healthcheck is also failing, but I do not know if this is a cause or a symptom of the above error.

HOST OS VERSION = balenaOS 2.83.10+rev1
SUPERVISOR VERSION = 12.9.3

**Comment by 20k-ultra** [comment]
I am working on a PR right now that should improve the logging for this.

closing in favor of https://github.com/balena-os/balena-supervisor/issues/1680
