### ISSUE TITLE
User requests BALENA_DEVICE_NAME_AT_INIT service env var be automatically updated on deviceName change

### ISSUE THREAD

**Issue by cywang117** [balena-os/balena-supervisor#1904]
Currently, DEVICE_NAME_AT_INIT is equal to the value of `name` in the database's `config` table. This env var changes on recreating containers manually, but the containers do not automatically get recreated on device name change.

**Comment by pipex** [comment]
The var is `DEVICE_NAME_AT_INIT`, which I think it means the name of the device when first provisioned. My understanding is that is the reason changing the name doesn't restart the containers.

**Comment by oscarkache** [comment]
The name is not updated on restart of the containers. DEVICE_NAME_AT_INIT only changes if I push another release onto the device.

**Comment by cywang117** [comment]
@oscarkache Restarting the container, if you do it through `balena restart` on the device, does not recreate the containers. Try curling Supervisor's /v1/restart API endpoint, which recreates the containers by default. I observed the recreation of services with the updated DEVICE_NAME_AT_INIT when the containers are recreated.

**Comment by pipex** [comment]
Ok, I got it wrong. `DEVICE_NAME_AT_INIT` is the name of the device at the beginning of the container lifetime, which I understand can get confusing. I would be against having the device name change trigger a restart of the container. Changing the app name has that effect and it has been known to cause confusion. 

Using the `/v2/device/name` API endpoint should be the recommended way to get the device name.

**Comment by cywang117** [comment]
Closing as /v2/device/name is the public interface for getting the device name.
