### ISSUE TITLE
Reboot and shutdown with SV endpoints prevents container from being restarted

### ISSUE THREAD

**Issue by pipex** [balena-os/balena-supervisor#1940]
In PR #1926 we moved to use the container data as a signal that the container needs to be restarted, this means that on reboot and on service crash, the engine will restart the service depending on the defined restart policy. This also means that if the service is deliberately stopped, then it won't be restarted automatically.

The problem is that the `/v1/reboot` and `/v1/shutdown` endpoints stop the containers before shutting down the system, meaning the containers won't be restarted by the engine on reboot.

The solution is to just make a call to reboot (if there are no update locks set) and let the engine send the termination signals to the containers.

**Comment by 20k-ultra** [comment]
Minor clarification, this issue only happens for containers with `unless-stopped` restart policy.

**Comment by pipex** [comment]
Are you sure? If you call `docker stop` on a container, even with `restart: always`, it won't be restarted automatically, will it?

```
cid=$(docker run -d --restart=always alpine sleep infinity)
docker stop $cid # container will stop and won't be restarted by the engine
```

**Comment by pipex** [comment]
Nevermind, I think you are right https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy
