### ISSUE TITLE
Wait for config.json writes to finish on provision before allowing shutdown

### ISSUE THREAD

**Issue by cywang117** [balena-os/balena-supervisor#1941]
The Supervisor shouldn't perform any actions that result in stopping itself, such as reboot or shutdown, during config.json writes. This will minimize the chances of the file becoming corrupt due to early shutdown. If a user calls /v1/shutdown on the device while a config.json write is happening, the shutdown process is not aware of the config.json write happening, and so if the write takes longer than the shutdown, shutdown will occur before the write completes. Simplified example of how this could occur:
```
const { promisify } = require('util');
const sleep = promisify(setTimeout);

const shutdown = async () => {
    console.log('starting shutdown');
    await sleep(500);
    console.log('shutting down');
    process.exit(0);
}

const writeToConfigJSON = async () => {
    console.log('starting config.json write');
    await sleep(1000);
    console.log('finished writing');
}

(async () => {
    writeToConfigJSON();
    shutdown();
})();
```

When running this code, you'll get the following logs:
```
starting config.json write
starting shutdown
shutting down
```

As you can see, in a case where writing takes longer to complete than shutting down, the config.json write never completes. If this issue happens during device provision, the config.json will become corrupt, soft-bricking the device.

This can be implemented as adding an update lock during config.json writes, or by explicitly syncing the boot partition before rebooting or shutting down.

**Comment by pipex** [comment]
I don’t think update locks are the right mechanism for internal locking, but I agree some sort of lock is the way to solve this on the short term. 

Long term the way is to have all device modifications be done through target state and the state engine. Right now we have independent control mechanisms  which can cause this sort of edge scenario.

**Comment by alexgg** [comment]
@cywang117 the shutdown will sync the filesystem, so `config.json` will not contain all the changes but it won't be corrupted. I remember discussion this in an arch call and my impression was that the provisioning mechanism as designed is already atomic. I'll need to find the recording and go back to it, but I think we should clarify that before merging.

**Comment by pipex** [comment]
@cywang117 do you think we can close this on account of https://github.com/balena-os/balena-supervisor/pull/1971?

**Comment by cywang117** [comment]
I think this would be good to close, especially with @alexgg's clarifications above 👍🏼 🙏🏼
