### ISSUE TITLE
`Applying boot config {}` loop without reboot when `balena-logo-default.png` is size 0

### ISSUE THREAD

**Issue by cywang117** [balena-os/balena-supervisor#1982]
Supervisor v13.1.6.

The Supervisor on the device will keep on logging `Applying boot config {}` very rapidly, additionally with:  `Expected splash image to be a base64 encoded PNG image. Skipping write.`. The device will be trying to apply some config.txt changes. I think the splash image fix in [v13.1.6](https://github.com/balena-os/balena-supervisor/blob/master/CHANGELOG.md#v1316) didn't work completely for some edge cases.

`cp /mnt/boot/splash/balena-logo.png /mnt/boot/splash/balena-logo-default.png` resolved the issue.

This is most likely due to a boot write for splash image getting interrupted, as the `vfat` boot partition is not atomic for writes.

**Comment by cywang117** [comment]
Please comment here if you still encounter this issue after [Supervisor v14.4.0](https://github.com/balena-os/balena-supervisor/blob/master/CHANGELOG.md#v1440), otherwise please see if upgrading to Supervisor 14.4.0 resolves the issue. We moved to using a better method for writing to the boot partition with 14.4.0 which should help reduce instances of this issue, if not eliminate it.

**Comment by jpmeijers** [comment]
I'm affected by this after updating from an old v2.x Baleno OS. Currently running supervisor v14.11.12 and Balena OS v3.1.0 and still being affected by this issue.

**Comment by barribarrier** [comment]
This just happened to 1 newly provisioned device of mine running balenaOS 5.1.5+rev1 and supervisor 15.0.4
SSH-ing into device and `ls -lh /mnt/boot/splash` shows:
```
total 6.0K
-rwxr-xr-x 1 root root    0 Jan 16 15:06 balena-logo-default.png
-rwxr-xr-x 1 root root 5.9K Jan 16 15:05 balena-logo.png
```
