### ISSUE TITLE
Investigate how unsupported device configs behave on older Supervisors

### ISSUE THREAD

**Issue by cywang117** [balena-os/balena-supervisor#2046]
When an unsupported `config.txt` variable is passed through target state and received by a Supervisor that doesn't explicitly support it, the behavior on the device is undefined and/or unexpected. We should look into whether the behavior on the device is recoverable. 

This issue will document these undefined behaviors to serve as a reference.

**Comment by pipex** [comment]
Tested this with supervisor 8.0.0 and balenaOS 2.26.0. When given an unknown format for a config variable, the supervisor rejects the target state, at least coming from the `/v2/local/target-state` endpoint

**Comment by pipex** [comment]
State validation seems to have been introduced here, with multi-app https://github.com/balena-os/balena-supervisor/commit/f77d3e15638b20230629aa5274afb18140ff0fef#diff-33390a6675cc73291f322333980c530714faa57fa99e4f443bacdcab6a8136a7R21-R28
