### ISSUE TITLE
Expose Balena Release Commit as Default Environment Variable

### ISSUE THREAD

**Issue by kendallgoto** [balena-os/balena-supervisor#2066]
Presently, a given container is provided with a multitude of useful default environment variables, including the app ID, device UUID, balenaOS version, etc.

https://github.com/balena-os/balena-supervisor/blob/48fca82a7993dd7334ae336d3632de1d4d680b76/src/compose/service.ts#L1001-L1009

However, this set of default environment variables lacks the "commit" or release version of the parent SW that is running within the container. Thus, the only way to get this information is with a relatively costly web call to the Balena Supervisor API. This is both a slow and unreliable way to retrieve basic information about a container from within the container.

The commit information is present in the code that calls `extendEnvVars`, so it only needs to be passed in order to release this valuable information to the container:
https://github.com/balena-os/balena-supervisor/blob/48fca82a7993dd7334ae336d3632de1d4d680b76/src/compose/service.ts#L144
https://github.com/balena-os/balena-supervisor/blob/48fca82a7993dd7334ae336d3632de1d4d680b76/src/compose/service.ts#L282-L286

With this change made, the commit info will be gracefully passed into the container and exposed as an environment variable.

**Comment by pipex** [comment]
@kendallgoto Unfortunately we cannot do that. Not all services change between releases. In that case, the supervisor keeps the unchanged release running by just changing its name. Having the release commit be an environment variable would mean that all the services would have to get restarted between releases, which is not ideal for many of our users.

If you need to get the current commit, the recommended way is to use the [supervisor API](https://www.balena.io/docs/reference/supervisor/supervisor-api/#get-v2applicationsappidstate)
