### ISSUE TITLE
Refreshing global API key with POST /v1/regenerate-api-key doesn't update /mnt/boot/config.json's deviceApiKey

### ISSUE THREAD

**Issue by cywang117** [balena-os/balena-supervisor#2080]
config.json retains the old API key, although the cloud API key that the backend uses to authenticate with the Supervisor should be updated. Is the deviceApiKey of config.json always supposed to be the same as the cloud API key? The endpoint doesn't make this clear.

**Comment by pipex** [comment]
The endpoint regenerates the key that containers can use to authenticate with the supervisor API, which is different from the deviceApiKey, which is what the supervisor and containers can use to authenticate with the backend API
