### ISSUE TITLE
Support `since` and `until` in Balena Supervisor API 

### ISSUE THREAD

**Issue by rkeulemans** [balena-os/balena-supervisor#2083]
The currently implemented API endpoint contains a [subset](https://www.balena.io/docs/reference/supervisor/supervisor-api/#journald-logs) of the `journalctl` functionality. To retrieve logs within a closed time interval without manually filtering all retrieved logs, support for `since` and `until` is welcome.

**Comment by pipex** [comment]
Hi @rkeulemans, thanks for the issue and creating the PR. I was curious about the reasons you prefer using the supervisor API instead of querying the journal directly using the `io.balena.features.journal-logs` [label](https://docs.balena.io/reference/supervisor/docker-compose/#labels) in your container configuration. 

We are always looking for ways to slimming down the supervisor codebase (for instance, by removing redundant features in a future v3 API). So I'd be interested to know how do you use this endpoint.

**Comment by rkeulemans** [comment]
@pipex

- We are not allowed to mount the root file system (only the Balena Supervisor is able to so), so we cannot use the host os `journalctl` directly.
- If we want to use `journalctl` from our container and use the suggested `io.balena.features.journal-logs` label, we need to have a container that has `systemd` (e.g. Debian). We prefer to use small/minimal images to make updates small and have less possible security vulnerabilities (e.g. Alpine) that do not have/support `systemd`. Therefore we resort to use the Supervisor API for this.

**Comment by pipex** [comment]
Thanks for the reply @rkeulemans. These are the same arguments that I have to want to remove this feature from the supervisor 

> We are not allowed to mount the root file system (only the Balena Supervisor is able to so), so we cannot use the host os journalctl directly.

We are trying to move towards making the supervisor work as any other Balena app, which will means no more access to the root filesystem. That's the reason behind this PR https://github.com/balena-os/balena-supervisor/pull/2069

> If we want to use journalctl from our container and use the suggested io.balena.features.journal-logs label, we need to have a container that has systemd (e.g. Debian). We prefer to use small/minimal images to make updates small and have less possible security vulnerabilities (e.g. Alpine) that do not have/support systemd. Therefore we resort to use the Supervisor API for this.

This is also true if we need to access the logs from the supervisor, except is true for all devices using the supervisor. 

I do see your point though. I think probably a future solution may be on having an optional block/container that is easy to use and that allows users easy access to the logs without having to install systemd themselves, but it can be removed if the user does not need direct access to the journal. I need to give this some more thought though.
