### ISSUE TITLE
Log backfilling is racy when starting a container

### ISSUE THREAD

**Issue by pipex** [balena-os/balena-supervisor#2260]
This can be replicated in local mode pushing the following dockerfile and start script

```
# Dockerfile
FROM alpine

COPY run.sh /
RUN chmod 755 /run.sh

CMD ["/run.sh"]
```

```
#!/bin/sh
# run.sh

echo "Container started 1"
echo "PID: $$ time" "$(date +"%T.%N")"
sleep infinity
```

When [backfilling on a new container](https://github.com/balena-os/balena-supervisor/blob/master/src/logging/monitor.ts#L152), the supervisor queries the journal with `Date.now()` as the value of `lastSentTimestamp`, but because the time sources are not exactly synchronized, the journal ends up returning the new lines as if they were backfilled, causing the user to see same lines twice 

```
[Logs]    [2024-04-04T16:05:41.765Z] [main] Container started 9
[Logs]    [2024-04-04T16:05:41.769Z] [main] PID: 1 time 16:05:41.
[Logs]    [2024-04-04T16:05:41.765Z] [main] Container started 9
[Logs]    [2024-04-04T16:05:41.769Z] [main] PID: 1 time 16:05:41.
```  

Using 1 second of delay when querying the journal works, although there might be a more nuanced solution.

**Comment by cywang117** [comment]
Same issue as https://github.com/balena-os/balena-supervisor/issues/1739

**Comment by pipex** [comment]
Log backfill was removed in #2351
