### ISSUE TITLE
expose getSysInfo on the supervisor api?

### ISSUE THREAD

**Issue by yuriploc** [balena-os/balena-supervisor#2297]
Hello there, let me know if this request should be asked somewhere else.

I'm interested in calling the supervisor API (`getSysInfo`) from a container to get the device state instead of calling `api.balena-cloud.com` and risk being rate limited.

Would that be possible?

**Comment by cywang117** [comment]
This is an existing issue here: https://github.com/balena-os/balena-supervisor/issues/1710

It's in our backlog, please follow that issue for progress. Thanks!
