### ISSUE TITLE
Exposing UDP ports causes a service to be continually restarted

### ISSUE THREAD

**Issue by pcarranzav** [balena-os/balena-supervisor#621]
Seen in supervisor 7.1.18.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_andv)

**Comment by pevecyan** [comment]
Hi @pcarranzav , may I ask when this fix will be pushed, and if until then, we should use previous version of image to avoid this problem?

**Comment by pcarranzav** [comment]
@pevecyan sadly previous versions would also be affected by this issue. I've already PRd the fix, so it will now take a day or two to get it tested and merged - after that we can already do supervisor updates to devices where this is relevant, while we go through the OS release process which also takes a while.
