### ISSUE TITLE
Add richer support for docker-compose networking

### ISSUE THREAD

**Issue by CameronDiver** [balena-os/balena-supervisor#709]
Currently only very simple networks are supported.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_dwyj)

**Comment by blackjid** [comment]
With the closing of #631, is there any time we can expect to use `network_mode: service:[name]` as described at https://forums.balena.io/t/connect-to-external-vpn/3784

thanks!

**Comment by CameronDiver** [comment]
I can't give a definitely time frame, but I've got a good handle on what needs to be done, and the other refactoring going on with this handling recently has definitely make the task easier. 

I've got a few pressing things that I'm currently working on, but once they're out of the way it'd be good to get this done directly afterwards.

**Comment by CameronDiver** [comment]
@blackjid just to keep you updated, I did a first pass at adding `network_mode: service:<servicename>` support here: https://github.com/balena-io/balena-supervisor/pull/1036

**Comment by blackjid** [comment]
thanks!!

**Comment by cywang117** [comment]
Closed with https://github.com/balena-os/balena-supervisor/pull/1036 and available with [Supervisor v10.1.0](https://github.com/balena-os/balena-supervisor/blob/master/CHANGELOG.md#v1010)
