### ISSUE TITLE
The supervisor sends spurious data to the state endpoint

### ISSUE THREAD

**Issue by CameronDiver** [balena-os/balena-supervisor#740]
An example is: 
```
{ local: { update_pending: true } }
```

This is not needed or used by the API, and shouldn't be sent.

**Comment by pipex** [comment]
I don't think this is true anymore https://github.com/balena-os/balena-supervisor/blob/a482174aa0c69d8fca3da83a751fd375f1b65dd9/src/device-state.ts#L487-L492

Closing
