### ISSUE TITLE
Feature request: API proxy inside the supervisor

### ISSUE THREAD

**Issue by imrehg** [balena-os/balena-supervisor#848]
Containers can just make requests to the backend API through the supervisor, and it would proxy it (sending the right endpoint, adding authentication). Possibly adding smarter stuff like handling device being offline, etc.

Also could add it such, that an SDK can be pointed at the supervisor's endpoint (instead of the backend directly), and work as it did before.

Discussed in the product call of 2018-12-13.

**Comment by cywang117** [comment]
It's unclear what the benefit of this is over querying the backend API directly by providing containers with the `io.balena.features.balena-api` compose feature label. As such, I'm closing this issue. If there is an updated use case for this feature request, please create a request through our public roadmap at roadmap.balena.io. Thanks!
