### ISSUE TITLE
Allow toggling the public URL from the supervisor API

### ISSUE THREAD

**Issue by CameronDiver** [balena-os/balena-supervisor#997]
This should be a simple call to the backend, to enable the public url on the device resource. Should also provide an endpoint to detail the state of the public url.

**Comment by cywang117** [comment]
Closing as it's unclear what the benefit of this is, over enabling the `io.balena.features.balena-api` label and using the [disable device URL](https://docs.balena.io/reference/sdk/node-sdk/#balena.models.device.disableDeviceUrl) SDK method (which may also be translated into a direct API call if desired).
